name: Lab 4 Workflow
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Robot is working!"
      - name: Break it
        run: exit 1
